# Generated by Django 5.2.17 on 2026-08-18 02:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('links', models.JSONField(default=dict)),
                ('original_release', models.DateField(blank=True, null=True)),
                ('game_name_slug', models.TextField(unique=True)),
                ('source_notes', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('set_name_slug', models.TextField(unique=True)),
                ('source_notes', models.JSONField(default=dict)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameitems.games')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_name', models.TextField()),
                ('attributes', models.JSONField(default=dict)),
                ('images', models.JSONField(default=dict)),
                ('source_notes', models.JSONField(default=dict)),
                ('functional_name', models.TextField()),
                ('item_name_slug', models.TextField(unique=True)),
                ('imaged', models.BooleanField(blank=True, null=True)),
                ('documented', models.BooleanField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameitems.games')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameitems.sets')),
            ],
        ),
    ]
