# Generated by Django 5.2.17 on 2026-08-18 02:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='Sets',
            new_name='Set',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('attributes', models.JSONField(default=dict)),
                ('images', models.JSONField(default=dict)),
                ('source_notes', models.JSONField(default=dict)),
                ('functional_name', models.TextField()),
                ('item_name_slug', models.TextField(unique=True)),
                ('imaged', models.BooleanField(blank=True, null=True)),
                ('documented', models.BooleanField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameitems.game')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameitems.set')),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
