# Generated by Django 5.2.17 on 2026-08-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0002_rename_games_game_rename_sets_set_item_delete_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='source_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
