# Generated by Django 5.2.17 on 2026-08-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0003_alter_game_source_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='set',
            name='source_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
