# Generated by Django 5.2.17 on 2026-08-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0004_alter_item_source_notes_alter_set_source_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='release_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='release_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='release_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
