# Generated by Django 5.2.17 on 2026-08-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0005_game_release_day_game_release_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='release_date',
        ),
    ]
