# Generated by Django 5.2.17 on 2026-08-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0006_remove_set_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.TextField(default='third-party-document'),
            preserve_default=False,
        ),
    ]
