# Generated by Django 5.2.17 on 2026-08-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0008_artist_collection_user_alter_game_links_item_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='owner_id',
            new_name='owner_user',
        ),
    ]
