# Generated by Django 5.2.17 on 2026-08-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0009_rename_owner_id_collection_owner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release_day',
            new_name='original_release_day',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='release_month',
            new_name='original_release_month',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='release_year',
            new_name='original_release_year',
        ),
        migrations.RemoveField(
            model_name='game',
            name='original_release',
        ),
        migrations.AddField(
            model_name='game',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='has_english_release',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='in_scope',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_competitive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_extant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_independently_customized',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='published_name',
            field=models.TextField(default='Rage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='related_game_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
