# Generated by Django 5.2.17 on 2026-08-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0010_rename_release_day_game_original_release_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='set_name_slug',
            new_name='game_set_slug',
        ),
        migrations.AddField(
            model_name='set',
            name='expected_item_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='publishers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='set',
            name='released',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
