# Generated by Django 5.2.17 on 2026-08-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0011_rename_set_name_slug_set_game_set_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_extant',
            new_name='is_dead',
        ),
    ]
