# Generated by Django 5.2.17 on 2026-08-21 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0012_rename_is_extant_game_is_dead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_competitive',
        ),
    ]
