# Generated by Django 5.2.17 on 2026-08-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0013_remove_game_is_competitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='documented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='imaged',
            field=models.BooleanField(default=False),
        ),
    ]
