# Generated by Django 5.2.17 on 2026-08-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameitems', '0014_alter_item_documented_alter_item_imaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='printed_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='artist',
            name='source_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
